// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prescription.Models;

#nullable disable

namespace Prescription.Migrations
{
    [DbContext(typeof(PrescriptionContext))]
    partial class PrescriptionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prescription.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("FillStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            Cost = 19.989999999999998,
                            FillStatus = "New",
                            MedicationName = "Atorvastatin",
                            RequestTime = new DateTime(2024, 10, 1, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionId = 2,
                            Cost = 12.5,
                            FillStatus = "Filled",
                            MedicationName = "Lisinopril",
                            RequestTime = new DateTime(2024, 11, 2, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionId = 3,
                            Cost = 8.75,
                            FillStatus = "Pending",
                            MedicationName = "Metformin",
                            RequestTime = new DateTime(2024, 12, 12, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
